"""new database connection and tables re-created

Revision ID: 0a3716c5e1fc
Revises: 
Create Date: 2026-07-18 18:48:46.679040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3716c5e1fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='roleenum'), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'blocked', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='roleenum'), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'blocked', name='verificationstatus'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_id'), 'email_otps', ['id'], unique=True)
    op.create_table('grade_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_grade_levels_id'), 'grade_levels', ['id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('file_category', sa.Enum('PROFILE_IMAGE', 'LEARNING_MATERIAL', name='filecategory'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=True)
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_table('hi_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hi_sections_grade_level_id'), 'hi_sections', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_hi_sections_id'), 'hi_sections', ['id'], unique=True)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', name='usersex'), nullable=True),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('student_type', sa.Enum('regular', 'HI', name='studenttype'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_image_id', sa.Integer(), nullable=True),
    sa.Column('guardians_name', sa.String(), nullable=True),
    sa.Column('guardians_contact_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ),
    sa.ForeignKeyConstraint(['profile_image_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['hi_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_account_id'), 'student_profiles', ['account_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_grade_level_id'), 'student_profiles', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_profiles_profile_image_id'), 'student_profiles', ['profile_image_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_section_id'), 'student_profiles', ['section_id'], unique=False)
    op.create_table('teacher_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('school_year', sa.String(length=30), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['hi_sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject', 'grade_level_id', 'section_id', name='uq_teacher_class_subject_grade_section')
    )
    op.create_index(op.f('ix_teacher_classes_grade_level_id'), 'teacher_classes', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_teacher_classes_id'), 'teacher_classes', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_classes_section_id'), 'teacher_classes', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_classes_teacher_id'), 'teacher_classes', ['teacher_id'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_image_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', name='usersex'), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_image_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index(op.f('ix_teacher_profiles_account_id'), 'teacher_profiles', ['account_id'], unique=True)
    op.create_index(op.f('ix_teacher_profiles_id'), 'teacher_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_profile_image_id'), 'teacher_profiles', ['profile_image_id'], unique=True)
    op.create_table('teacher_grade_handles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_grade_handles_grade_level_id'), 'teacher_grade_handles', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_teacher_grade_handles_id'), 'teacher_grade_handles', ['id'], unique=True)
    op.create_index(op.f('ix_teacher_grade_handles_teacher_id'), 'teacher_grade_handles', ['teacher_id'], unique=False)
    op.create_table('teacher_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=True),
    sa.Column('week', sa.String(length=30), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=120), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('behavior_required', sa.String(length=10), nullable=False),
    sa.Column('estimated_time', sa.String(length=30), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['teacher_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_modules_class_id'), 'teacher_modules', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_modules_id'), 'teacher_modules', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_modules_teacher_id'), 'teacher_modules', ['teacher_id'], unique=False)
    op.create_table('learning_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('page_image_urls', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['teacher_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_topics_id'), 'learning_topics', ['id'], unique=False)
    op.create_index(op.f('ix_learning_topics_module_id'), 'learning_topics', ['module_id'], unique=False)
    op.create_table('student_topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['teacher_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['learning_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'topic_id', name='uq_student_topic_progress')
    )
    op.create_index(op.f('ix_student_topic_progress_id'), 'student_topic_progress', ['id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_module_id'), 'student_topic_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_student_id'), 'student_topic_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_topic_id'), 'student_topic_progress', ['topic_id'], unique=False)
    op.create_table('teacher_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('week', sa.String(length=30), nullable=True),
    sa.Column('time_limit', sa.String(length=30), nullable=True),
    sa.Column('attempts_allowed', sa.Integer(), nullable=False),
    sa.Column('shuffle_questions', sa.String(length=10), nullable=False),
    sa.Column('show_answers_after_submission', sa.String(length=10), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['teacher_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['teacher_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['learning_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_assessments_assessment_type'), 'teacher_assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_teacher_assessments_class_id'), 'teacher_assessments', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_assessments_id'), 'teacher_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_assessments_module_id'), 'teacher_assessments', ['module_id'], unique=False)
    op.create_index(op.f('ix_teacher_assessments_teacher_id'), 'teacher_assessments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_assessments_topic_id'), 'teacher_assessments', ['topic_id'], unique=False)
    op.create_table('student_quiz_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['teacher_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['teacher_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assessment_id', name='uq_student_quiz_progress')
    )
    op.create_index(op.f('ix_student_quiz_progress_assessment_id'), 'student_quiz_progress', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_student_quiz_progress_id'), 'student_quiz_progress', ['id'], unique=False)
    op.create_index(op.f('ix_student_quiz_progress_module_id'), 'student_quiz_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_student_quiz_progress_student_id'), 'student_quiz_progress', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_quiz_progress_student_id'), table_name='student_quiz_progress')
    op.drop_index(op.f('ix_student_quiz_progress_module_id'), table_name='student_quiz_progress')
    op.drop_index(op.f('ix_student_quiz_progress_id'), table_name='student_quiz_progress')
    op.drop_index(op.f('ix_student_quiz_progress_assessment_id'), table_name='student_quiz_progress')
    op.drop_table('student_quiz_progress')
    op.drop_index(op.f('ix_teacher_assessments_topic_id'), table_name='teacher_assessments')
    op.drop_index(op.f('ix_teacher_assessments_teacher_id'), table_name='teacher_assessments')
    op.drop_index(op.f('ix_teacher_assessments_module_id'), table_name='teacher_assessments')
    op.drop_index(op.f('ix_teacher_assessments_id'), table_name='teacher_assessments')
    op.drop_index(op.f('ix_teacher_assessments_class_id'), table_name='teacher_assessments')
    op.drop_index(op.f('ix_teacher_assessments_assessment_type'), table_name='teacher_assessments')
    op.drop_table('teacher_assessments')
    op.drop_index(op.f('ix_student_topic_progress_topic_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_student_topic_progress_student_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_student_topic_progress_module_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_student_topic_progress_id'), table_name='student_topic_progress')
    op.drop_table('student_topic_progress')
    op.drop_index(op.f('ix_learning_topics_module_id'), table_name='learning_topics')
    op.drop_index(op.f('ix_learning_topics_id'), table_name='learning_topics')
    op.drop_table('learning_topics')
    op.drop_index(op.f('ix_teacher_modules_teacher_id'), table_name='teacher_modules')
    op.drop_index(op.f('ix_teacher_modules_id'), table_name='teacher_modules')
    op.drop_index(op.f('ix_teacher_modules_class_id'), table_name='teacher_modules')
    op.drop_table('teacher_modules')
    op.drop_index(op.f('ix_teacher_grade_handles_teacher_id'), table_name='teacher_grade_handles')
    op.drop_index(op.f('ix_teacher_grade_handles_id'), table_name='teacher_grade_handles')
    op.drop_index(op.f('ix_teacher_grade_handles_grade_level_id'), table_name='teacher_grade_handles')
    op.drop_table('teacher_grade_handles')
    op.drop_index(op.f('ix_teacher_profiles_profile_image_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_account_id'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_teacher_classes_teacher_id'), table_name='teacher_classes')
    op.drop_index(op.f('ix_teacher_classes_section_id'), table_name='teacher_classes')
    op.drop_index(op.f('ix_teacher_classes_id'), table_name='teacher_classes')
    op.drop_index(op.f('ix_teacher_classes_grade_level_id'), table_name='teacher_classes')
    op.drop_table('teacher_classes')
    op.drop_index(op.f('ix_student_profiles_section_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_profile_image_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_grade_level_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_account_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_hi_sections_id'), table_name='hi_sections')
    op.drop_index(op.f('ix_hi_sections_grade_level_id'), table_name='hi_sections')
    op.drop_table('hi_sections')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_grade_levels_id'), table_name='grade_levels')
    op.drop_table('grade_levels')
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
