"""new teacher_profile fields added

Revision ID: 0d31089ac662
Revises: 7a7b2c4ca388
Create Date: 2026-06-27 17:14:54.742662

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d31089ac662'
down_revision: Union[str, Sequence[str], None] = '7a7b2c4ca388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    usersex_enum = postgresql.ENUM(
        "Male",
        "Female",
        name="usersex"
    )

    gradelevel_enum = postgresql.ENUM(
        "grade_1",
        "grade_2",
        "grade_3",
        "grade_4",
        "grade_5",
        "grade_6",
        name="gradelevel"
    )
    op.add_column('teacher_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('teacher_profiles', sa.Column('sex', sa.Enum('Male', 'Female', name='usersex'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'sex')
    op.drop_column('teacher_profiles', 'age')

    gradelevel_enum = postgresql.ENUM(
        name="gradelevel"
    )

    usersex_enum = postgresql.ENUM(
        name="usersex"
    )

    gradelevel_enum.drop(op.get_bind(), checkfirst=True)
    usersex_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
