"""verification status added in email otp

Revision ID: 2e83dc2117bc
Revises: 14ffb227d011
Create Date: 2026-07-08 17:35:01.691641

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

verification_status_enum = postgresql.ENUM(
    "pending",
    "verified",
    "blocked",
    name="verificationstatus",
)


# revision identifiers, used by Alembic.
revision: str = '2e83dc2117bc'
down_revision: Union[str, Sequence[str], None] = '14ffb227d011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    
    verification_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('email_otps', sa.Column('verification_status', sa.Enum('pending', 'verified', 'blocked', name='verificationstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_otps', 'verification_status')
    verification_status_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('accounts', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
