"""add_centralized_academic_structure

Revision ID: 315f96f17b70
Revises: 7dac31640e29
Create Date: 2026-07-11 14:39:08.292490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '315f96f17b70'
down_revision: Union[str, Sequence[str], None] = '7dac31640e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='sectionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_grade_levels_id'), 'grade_levels', ['id'], unique=False)
    op.create_index(op.f('ix_grade_levels_status'), 'grade_levels', ['status'], unique=False)
    op.create_table('school_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='sectionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_school_years_id'), 'school_years', ['id'], unique=False)
    op.create_index(op.f('ix_school_years_status'), 'school_years', ['status'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='sectionstatusenum'), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_grade_level_id'), 'sections', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_school_year_id'), 'sections', ['school_year_id'], unique=False)
    op.create_index(op.f('ix_sections_status'), 'sections', ['status'], unique=False)
    op.create_index(op.f('ix_sections_teacher_id'), 'sections', ['teacher_id'], unique=False)
    op.create_table('teacher_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('previous_teacher_id', sa.Integer(), nullable=True),
    sa.Column('new_teacher_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_teacher_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_teacher_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_assignment_history_id'), 'teacher_assignment_history', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_assignment_history_new_teacher_id'), 'teacher_assignment_history', ['new_teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignment_history_previous_teacher_id'), 'teacher_assignment_history', ['previous_teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignment_history_section_id'), 'teacher_assignment_history', ['section_id'], unique=False)
    op.add_column('student_profiles', sa.Column('grade_level_id', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('section_id', sa.Integer(), nullable=True))
    op.alter_column('student_profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profiles', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', name='usersex'),
               nullable=True)
    op.alter_column('student_profiles', 'student_type',
               existing_type=postgresql.ENUM('regular', 'HI', name='studenttype'),
               nullable=True)
    op.alter_column('student_profiles', 'grade_level',
               existing_type=postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('student_profiles', 'section',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.create_index(op.f('ix_student_profiles_grade_level_id'), 'student_profiles', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_section_id'), 'student_profiles', ['section_id'], unique=False)
    op.create_foreign_key(None, 'student_profiles', 'grade_levels', ['grade_level_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'student_profiles', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_student_profiles_section_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_grade_level_id'), table_name='student_profiles')
    op.alter_column('student_profiles', 'section',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('student_profiles', 'grade_level',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'),
               nullable=False)
    op.alter_column('student_profiles', 'student_type',
               existing_type=postgresql.ENUM('regular', 'HI', name='studenttype'),
               nullable=False)
    op.alter_column('student_profiles', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', name='usersex'),
               nullable=False)
    op.alter_column('student_profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('student_profiles', 'section_id')
    op.drop_column('student_profiles', 'grade_level_id')
    op.drop_index(op.f('ix_teacher_assignment_history_section_id'), table_name='teacher_assignment_history')
    op.drop_index(op.f('ix_teacher_assignment_history_previous_teacher_id'), table_name='teacher_assignment_history')
    op.drop_index(op.f('ix_teacher_assignment_history_new_teacher_id'), table_name='teacher_assignment_history')
    op.drop_index(op.f('ix_teacher_assignment_history_id'), table_name='teacher_assignment_history')
    op.drop_table('teacher_assignment_history')
    op.drop_index(op.f('ix_sections_teacher_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_status'), table_name='sections')
    op.drop_index(op.f('ix_sections_school_year_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_grade_level_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_school_years_status'), table_name='school_years')
    op.drop_index(op.f('ix_school_years_id'), table_name='school_years')
    op.drop_table('school_years')
    op.drop_index(op.f('ix_grade_levels_status'), table_name='grade_levels')
    op.drop_index(op.f('ix_grade_levels_id'), table_name='grade_levels')
    op.drop_table('grade_levels')
    # ### end Alembic commands ###
