"""verification status added in accounts table

Revision ID: 61e51b4254fa
Revises: 2e83dc2117bc
Create Date: 2026-07-08 18:15:38.261119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e51b4254fa'
down_revision: Union[str, Sequence[str], None] = '2e83dc2117bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('verification_status', sa.Enum('pending', 'verified', 'blocked', name='verificationstatus'), nullable=True))
    op.drop_column('accounts', 'is_verified')
    op.alter_column('email_otps', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'blocked', name='verificationstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_otps', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'blocked', name='verificationstatus'),
               nullable=True)
    op.add_column('accounts', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'verification_status')
    # ### end Alembic commands ###
