"""fix migrations recent error

Revision ID: 6f702856c187
Revises: fe83ef85833a
Create Date: 2026-06-27 21:31:57.251125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f702856c187'
down_revision: Union[str, Sequence[str], None] = 'fe83ef85833a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teacher_grade_handles",
        "grade_level",
        new_column_name="grade_level_handles"
    )
    op.drop_index(op.f('ix_teacher_grade_handles_teacher_id'), table_name='teacher_grade_handles')
    op.create_index(op.f('ix_teacher_grade_handles_teacher_id'), 'teacher_grade_handles', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_grade_handles_teacher_id'), table_name='teacher_grade_handles')
    op.create_index(op.f('ix_teacher_grade_handles_teacher_id'), 'teacher_grade_handles', ['teacher_id'], unique=True)
    op.alter_column(
        "teacher_grade_handles",
        "grade_level",
        new_column_name="grade_level_handles"
    )
    # ### end Alembic commands ###
