"""nullable=False, sa new fields

Revision ID: 7a7b2c4ca388
Revises: cdf28a5d0aea
Create Date: 2026-06-27 15:30:45.645466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a7b2c4ca388'
down_revision: Union[str, Sequence[str], None] = 'cdf28a5d0aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_profiles', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', name='usersex'),
               nullable=False)
    op.alter_column('student_profiles', 'grade_level',
               existing_type=postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'),
               nullable=False)
    op.alter_column('student_profiles', 'section',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'section',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('student_profiles', 'grade_level',
               existing_type=postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'),
               nullable=True)
    op.alter_column('student_profiles', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', name='usersex'),
               nullable=True)
    op.alter_column('student_profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
