"""refactored EmailOTP table

Revision ID: 7ce7abe8aa84
Revises: 65e96ce92314
Create Date: 2026-07-07 22:38:59.496029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce7abe8aa84'
down_revision: Union[str, Sequence[str], None] = '65e96ce92314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_otps', 'role')
    op.drop_column('email_otps', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otps', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('email_otps', sa.Column('role', postgresql.ENUM('student', 'teacher', 'admin', name='roleenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
