"""omni admin foundation

Revision ID: 7dac31640e29
Revises: 0a3716c5e1fc
Create Date: 2026-07-04 18:48:09.339275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dac31640e29'
down_revision: Union[str, Sequence[str], None] = '0a3716c5e1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type manually since autogenerate missed it
    account_status_enum = sa.Enum('pending_activation', 'waiting_assignment', 'active', 'inactive', 'archived', name='accountstatusenum')
    account_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_status', account_status_enum, nullable=False))
    op.create_index(op.f('ix_accounts_account_status'), 'accounts', ['account_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_account_status'), table_name='accounts')
    op.drop_column('accounts', 'account_status')
    # ### end Alembic commands ###
