"""grade and section added in teacher class

Revision ID: 7f12045064b6
Revises: e01d2f8ab5a1
Create Date: 2026-07-14 15:20:24.280326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f12045064b6'
down_revision: Union[str, Sequence[str], None] = 'e01d2f8ab5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_classes', sa.Column('grade_level_id', sa.Integer(), nullable=True))
    op.add_column('teacher_classes', sa.Column('section_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_teacher_class_subject_grade_section'), 'teacher_classes', type_='unique')
    op.create_unique_constraint('uq_teacher_class_subject_grade_section', 'teacher_classes', ['teacher_id', 'subject', 'grade_level_id', 'section_id'])
    op.create_index(op.f('ix_teacher_classes_grade_level_id'), 'teacher_classes', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_teacher_classes_section_id'), 'teacher_classes', ['section_id'], unique=False)
    op.create_foreign_key(None, 'teacher_classes', 'hi_sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'teacher_classes', 'grade_levels', ['grade_level_id'], ['id'])
    op.drop_column('teacher_classes', 'grade_level')
    op.drop_column('teacher_classes', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_classes', sa.Column('section', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('teacher_classes', sa.Column('grade_level', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teacher_classes', type_='foreignkey')
    op.drop_constraint(None, 'teacher_classes', type_='foreignkey')
    op.drop_index(op.f('ix_teacher_classes_section_id'), table_name='teacher_classes')
    op.drop_index(op.f('ix_teacher_classes_grade_level_id'), table_name='teacher_classes')
    op.drop_constraint('uq_teacher_class_subject_grade_section', 'teacher_classes', type_='unique')
    op.create_unique_constraint(op.f('uq_teacher_class_subject_grade_section'), 'teacher_classes', ['teacher_id', 'subject', 'grade_level', 'section'], postgresql_nulls_not_distinct=False)
    op.drop_column('teacher_classes', 'section_id')
    op.drop_column('teacher_classes', 'grade_level_id')
    # ### end Alembic commands ###
