"""updated student profile

Revision ID: cdc1d777c365
Revises: def3a9781f03
Create Date: 2026-07-13 20:43:54.259630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc1d777c365'
down_revision: Union[str, Sequence[str], None] = 'def3a9781f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'grade_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profiles', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_student_profiles_grade_level_id'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_grade_level_id'), 'student_profiles', ['grade_level_id'], unique=False)
    op.drop_index(op.f('ix_student_profiles_section_id'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_section_id'), 'student_profiles', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_section_id'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_section_id'), 'student_profiles', ['section_id'], unique=True)
    op.drop_index(op.f('ix_student_profiles_grade_level_id'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_grade_level_id'), 'student_profiles', ['grade_level_id'], unique=True)
    op.alter_column('student_profiles', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profiles', 'grade_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
