"""student profile fields added

Revision ID: cdf28a5d0aea
Revises: 2118047d37c9
Create Date: 2026-06-27 15:10:47.952008

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf28a5d0aea'
down_revision: Union[str, Sequence[str], None] = '2118047d37c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    usersex_enum = postgresql.ENUM(
        "Male",
        "Female",
        name="usersex"
    )

    gradelevel_enum = postgresql.ENUM(
        "grade_1",
        "grade_2",
        "grade_3",
        "grade_4",
        "grade_5",
        "grade_6",
        name="gradelevel"
    )

    usersex_enum.create(op.get_bind(), checkfirst=True)
    gradelevel_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('student_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('sex', sa.Enum('Male', 'Female', name='usersex'), nullable=True))
    op.add_column('student_profiles', sa.Column('grade_level', sa.Enum('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'), nullable=True))
    op.add_column('student_profiles', sa.Column('section', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'section')
    op.drop_column('student_profiles', 'grade_level')
    op.drop_column('student_profiles', 'sex')
    op.drop_column('student_profiles', 'age')

    gradelevel_enum = postgresql.ENUM(
        name="gradelevel"
    )

    usersex_enum = postgresql.ENUM(
        name="usersex"
    )

    gradelevel_enum.drop(op.get_bind(), checkfirst=True)
    usersex_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
