"""grade_level and sections table created

Revision ID: d2ef8214e8f0
Revises: 3e6110e00823
Create Date: 2026-07-13 16:22:09.125437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ef8214e8f0'
down_revision: Union[str, Sequence[str], None] = '3e6110e00823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_grade_levels_id'), 'grade_levels', ['id'], unique=True)
    op.create_table('hi_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hi_sections_grade_level_id'), 'hi_sections', ['grade_level_id'], unique=False)
    op.create_index(op.f('ix_hi_sections_id'), 'hi_sections', ['id'], unique=True)
    op.alter_column('accounts', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'blocked', name='verificationstatus'),
               nullable=True)
    op.alter_column('student_profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profiles', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', name='usersex'),
               nullable=True)
    op.alter_column('student_profiles', 'grade_level',
               existing_type=postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'),
               nullable=True)
    op.alter_column('student_profiles', 'section',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'section',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('student_profiles', 'grade_level',
               existing_type=postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'),
               nullable=False)
    op.alter_column('student_profiles', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', name='usersex'),
               nullable=False)
    op.alter_column('student_profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accounts', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'blocked', name='verificationstatus'),
               nullable=True)
    op.drop_index(op.f('ix_hi_sections_id'), table_name='hi_sections')
    op.drop_index(op.f('ix_hi_sections_grade_level_id'), table_name='hi_sections')
    op.drop_table('hi_sections')
    op.drop_index(op.f('ix_grade_levels_id'), table_name='grade_levels')
    op.drop_table('grade_levels')
    # ### end Alembic commands ###
