"""table for otp, added columns

Revision ID: ddb2258ed421
Revises: 7ce7abe8aa84
Create Date: 2026-07-07 23:04:27.916087

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb2258ed421'
down_revision: Union[str, Sequence[str], None] = '7ce7abe8aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otps', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('email_otps', sa.Column('role', postgresql.ENUM('student', 'teacher', 'admin', name='roleenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_otps', 'role')
    op.drop_column('email_otps', 'email')
    # ### end Alembic commands ###
