"""grade level and section added in student_profile

Revision ID: def3a9781f03
Revises: d2ef8214e8f0
Create Date: 2026-07-13 18:48:59.340437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'def3a9781f03'
down_revision: Union[str, Sequence[str], None] = 'd2ef8214e8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'blocked', name='verificationstatus'),
               nullable=False)
    op.add_column('student_profiles', sa.Column('grade_level_id', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_profiles_grade_level_id'), 'student_profiles', ['grade_level_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_section_id'), 'student_profiles', ['section_id'], unique=True)
    op.create_foreign_key(None, 'student_profiles', 'grade_levels', ['grade_level_id'], ['id'])
    op.create_foreign_key(None, 'student_profiles', 'hi_sections', ['section_id'], ['id'])
    op.drop_column('student_profiles', 'grade_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('grade_level', postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_student_profiles_section_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_grade_level_id'), table_name='student_profiles')
    op.drop_column('student_profiles', 'section_id')
    op.drop_column('student_profiles', 'grade_level_id')
    op.alter_column('accounts', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'blocked', name='verificationstatus'),
               nullable=True)
    # ### end Alembic commands ###
