"""student profile nullable=True alternate to False

Revision ID: e01d2f8ab5a1
Revises: cdc1d777c365
Create Date: 2026-07-13 20:48:34.230643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01d2f8ab5a1'
down_revision: Union[str, Sequence[str], None] = 'cdc1d777c365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'grade_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_profiles', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('student_profiles', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('section', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.alter_column('student_profiles', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profiles', 'grade_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
