"""table for otp, column added (is_verified)

Revision ID: f1bd92f0bdb6
Revises: ddb2258ed421
Create Date: 2026-07-07 23:11:01.237794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1bd92f0bdb6'
down_revision: Union[str, Sequence[str], None] = 'ddb2258ed421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otps', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('email_otps', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_otps', 'role',
               existing_type=postgresql.ENUM('student', 'teacher', 'admin', name='roleenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_otps', 'role',
               existing_type=postgresql.ENUM('student', 'teacher', 'admin', name='roleenum'),
               nullable=True)
    op.alter_column('email_otps', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('email_otps', 'is_verified')
    # ### end Alembic commands ###
