"""teacher grade level handles table created

Revision ID: fe83ef85833a
Revises: 0d31089ac662
Create Date: 2026-06-27 17:20:10.083506

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe83ef85833a'
down_revision: Union[str, Sequence[str], None] = '0d31089ac662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('teacher_grade_handles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_level', postgresql.ENUM('grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', name='gradelevel', create_type=False), nullable=False,),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_grade_handles_id'), 'teacher_grade_handles', ['id'], unique=True)
    op.create_index(op.f('ix_teacher_grade_handles_teacher_id'), 'teacher_grade_handles', ['teacher_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_grade_handles_teacher_id'), table_name='teacher_grade_handles')
    op.drop_index(op.f('ix_teacher_grade_handles_id'), table_name='teacher_grade_handles')
    op.drop_table('teacher_grade_handles')

    # ### end Alembic commands ###
