CONFIDENCE_THRESHOLD = 0.75

LANDMARK_DETECTION_CONFIDENCE = 0.3
CAMERA_TRACKING_CONFIDENCE = 0.4

SMOOTHING_WINDOW = 5
MIRROR_FALLBACK_MARGIN = 0.05
SIGN_CHANGE_RESET_MARGIN = 0.12

PROBLEM_LABELS = {"J", "P", "Q", "R", "S", "T", "X", "Z"}
DYNAMIC_GESTURE_LABELS = {"J", "Z"}

DYNAMIC_GESTURE_WINDOW_SECONDS = 2.0
DYNAMIC_GESTURE_MIN_FRAMES = 8
DYNAMIC_GESTURE_DIRECT_FRAMES = 3
DYNAMIC_GESTURE_PRIMARY_PROBABILITY = 0.10
DYNAMIC_GESTURE_PRIMARY_PROBABILITIES = {"J": 0.10, "Z": 0.05}
DYNAMIC_GESTURE_SECONDARY_PROBABILITY = 0.04
DYNAMIC_GESTURE_COOLDOWN_SECONDS = 1.4

STATIC_CALIBRATION_CONFIDENCE = 0.76
M_CALIBRATION_MIN_PROBABILITY = 0.45
P_CALIBRATION_MIN_PROBABILITY = 0.22
P_CALIBRATION_CLOSE_MARGIN = 0.18
P_RELATED_LABELS = {"K", "P", "Q"}

CONFIRMATION_SECONDS = 3.0
POST_ACCEPT_COOLDOWN_SECONDS = 0.75
HAND_REMOVED_RESET_SECONDS = 0.75
DIFFERENT_SIGN_RESET_SECONDS = 0.75
