import re


SUPPORTED_SCIENCE_SIGNS = [
    "EARTH",
    "SUN",
    "MOON",
    "WATER",
    "OXYGEN",
    "PLANT",
    "ANIMAL",
    "GRAVITY",
    "ENERGY",
    "LIGHT",
    "HEAT",
    "SOLID",
    "LIQUID",
    "GAS",
    "FORCE",
    "PUSH",
    "PULL",
    "AIR",
    "INVENTION",
    "INVENTOR",
    "TECHNOLOGY",
    "FE_DEL_MUNDO",
    "BAMBOO",
    "DOCTOR",
    "GREGORIO_ZARA",
    "TELEPHONE",
    "KARAOKE",
    "LIGHT_BULB",
    "CHEMICAL_PROPERTY",
    "FLAMMABILITY",
    "REACTIVITY",
    "KEROSENE",
    "BLEACH",
    "MURIATIC_ACID",
    "RUSTING",
    "TOXICITY",
    "CORROSION",
    "EXPLOSIVE",
    "BIODEGRADABLE",
    "NON_BIODEGRADABLE",
    "BANANA_PEEL",
    "PLASTIC_BOTTLE",
    "COMPOSTING",
    "MICROORGANISMS",
    "ORGANIC_WASTE",
    "ALUMINUM_CAN",
    "GLASS_JAR",
    "DECOMPOSERS",
    "COMBUSTION",
    "IRREVERSIBLE_CHANGE",
    "ASH",
    "MELTING",
    "TEMPERATURE",
    "REVERSIBLE_CHANGE",
    "FREEZING",
    "EVAPORATION",
    "HEAT_ENERGY",
    "EXPANSION",
    "HARMFUL_CHANGE",
    "WASTE_MANAGEMENT",
    "TOXIC_FUMES",
    "PROPER_STORAGE",
    "RECYCLING",
    "REUSE",
    "REDUCE",
    "POLLUTION",
    "SAFETY_LABEL",
    "BIODEGRADABLE_PIT",
    "WATER_POLLUTION",
    "WASTE_TREATMENT",
    "SEGREGATION",
    "OPEN_MINDEDNESS",
    "ENVIRONMENTAL_ISSUE",
    "AIR_POLLUTION",
    "DEFORESTATION",
    "REFORESTATION",
    "SOIL_EROSION",
    "MATERIAL_RECOVERY",
    "SCIENCE_PROCESS_SKILLS",
    "OBSERVATION",
    "DATA_CLASSIFICATION",
    "SCIENTIFIC_SURVEY",
    "COMMUNICATION",
    "PREDICTION",
    "MEASUREMENT",
    "INFERENCE",
    "QUESTIONNAIRES",
    "DATA_ANALYSIS",
    "MATERIAL", "USEFUL_MATERIAL", "HARMFUL_MATERIAL", "TOXIC", "FLAMMABLE",
    "CORROSIVE", "SAFETY_SYMBOL", "EXPIRATION_DATE", "CONTAINER", "OXIDATION",
    "FIRE_TRIANGLE", "DECOMPOSING", "FRESH_APPLE", "IRON_OXIDE", "FUEL",
    "PHYSICAL_CHANGE", "CHEMICAL_CHANGE", "BURNING", "COOKING", "REVERSIBLE",
    "IRREVERSIBLE", "HEAT_APPLICATION", "MIXTURE", "HOMOGENEOUS", "HETEROGENEOUS",
    "COMPONENT", "HALO_HALO", "SUGAR_SOLUTION", "SOLID_SOLID", "LIQUID_LIQUID",
    "PHASE", "SOLUTION", "SOLUTE", "SOLVENT", "SUSPENSION", "COLLOID",
    "TYNDALL_EFFECT", "MUDDY_WATER", "MAYONNAISE", "DISSOLVING", "SETTLING",
]

WEEKLY_SCIENCE_SIGN_LABELS = {
    "WEEK1": [
        "TECHNOLOGY",
        "TELEPHONE",
        "LIGHT_BULB",
        "DOCTOR",
        "BAMBOO",
        "INVENTION",
        "INVENTOR",
        "FE_DEL_MUNDO",
        "GREGORIO_ZARA",
        "KARAOKE",
    ],
    "WEEK2": [
        "FLAMMABILITY",
        "CHEMICAL_PROPERTY",
        "REACTIVITY",
        "KEROSENE",
        "BLEACH",
        "MURIATIC_ACID",
        "RUSTING",
        "TOXICITY",
        "CORROSION",
        "EXPLOSIVE",
    ],
    "WEEK3": [
        "BIODEGRADABLE",
        "NON_BIODEGRADABLE",
        "BANANA_PEEL",
        "PLASTIC_BOTTLE",
        "COMPOSTING",
        "MICROORGANISMS",
        "ORGANIC_WASTE",
        "ALUMINUM_CAN",
        "GLASS_JAR",
        "DECOMPOSERS",
    ],
    "WEEK4": [
        "COMBUSTION",
        "IRREVERSIBLE_CHANGE",
        "ASH",
        "MELTING",
        "TEMPERATURE",
        "REVERSIBLE_CHANGE",
        "FREEZING",
        "EVAPORATION",
        "HEAT_ENERGY",
        "EXPANSION",
    ],
    "WEEK5": [
        "HARMFUL_CHANGE",
        "WASTE_MANAGEMENT",
        "TOXIC_FUMES",
        "PROPER_STORAGE",
        "RECYCLING",
        "REUSE",
        "REDUCE",
        "POLLUTION",
        "SAFETY_LABEL",
        "BIODEGRADABLE_PIT",
    ],
    "WEEK6": [
        "WATER_POLLUTION",
        "WASTE_TREATMENT",
        "SEGREGATION",
        "OPEN_MINDEDNESS",
        "ENVIRONMENTAL_ISSUE",
        "AIR_POLLUTION",
        "DEFORESTATION",
        "REFORESTATION",
        "SOIL_EROSION",
        "MATERIAL_RECOVERY",
    ],
    "WEEK7": [
        "SCIENCE_PROCESS_SKILLS",
        "OBSERVATION",
        "DATA_CLASSIFICATION",
        "SCIENTIFIC_SURVEY",
        "COMMUNICATION",
        "PREDICTION",
        "MEASUREMENT",
        "INFERENCE",
        "QUESTIONNAIRES",
        "DATA_ANALYSIS",
    ],
    "GRADE5_WEEK1": [
        "MATERIAL", "USEFUL_MATERIAL", "HARMFUL_MATERIAL", "TOXIC", "FLAMMABLE",
        "CORROSIVE", "BIODEGRADABLE", "SAFETY_SYMBOL", "EXPIRATION_DATE", "CONTAINER",
    ],
    "GRADE5_WEEK2": [
        "OXYGEN", "RUSTING", "OXIDATION", "COMBUSTION", "FIRE_TRIANGLE",
        "DECOMPOSING", "FRESH_APPLE", "IRON_OXIDE", "HEAT", "FUEL",
    ],
    "GRADE5_WEEK3": [
        "PHYSICAL_CHANGE", "CHEMICAL_CHANGE", "MELTING", "EVAPORATION", "BURNING",
        "COOKING", "REVERSIBLE", "IRREVERSIBLE", "ASH", "HEAT_APPLICATION",
    ],
    "GRADE6_WEEK1": [
        "MIXTURE", "HOMOGENEOUS", "HETEROGENEOUS", "COMPONENT", "PHYSICAL_CHANGE",
        "HALO_HALO", "SUGAR_SOLUTION", "SOLID_SOLID", "LIQUID_LIQUID", "PHASE",
    ],
    "GRADE6_WEEK2": [
        "SOLUTION", "SOLUTE", "SOLVENT", "SUSPENSION", "COLLOID", "TYNDALL_EFFECT",
        "MUDDY_WATER", "MAYONNAISE", "DISSOLVING", "SETTLING",
    ],
}

ANSWER_ALIASES = {
    "EARTH": ["EARTH", "THE EARTH", "WORLD"],
    "SUN": ["SUN", "THE SUN"],
    "MOON": ["MOON", "THE MOON"],
    "WATER": ["WATER", "H2O"],
    "OXYGEN": ["OXYGEN", "O2"],
    "PLANT": ["PLANT", "PLANTS"],
    "ANIMAL": ["ANIMAL", "ANIMALS"],
    "GRAVITY": ["GRAVITY"],
    "ENERGY": ["ENERGY"],
    "LIGHT": ["LIGHT"],
    "HEAT": ["HEAT"],
    "SOLID": ["SOLID"],
    "LIQUID": ["LIQUID"],
    "GAS": ["GAS"],
    "FORCE": ["FORCE"],
    "PUSH": ["PUSH"],
    "PULL": ["PULL"],
    "AIR": ["AIR"],
    "INVENTION": ["INVENTION"],
    "INVENTOR": ["INVENTOR"],
    "TECHNOLOGY": ["TECHNOLOGY"],
    "FE_DEL_MUNDO": ["FE DEL MUNDO", "FEDEL MUNDO", "DR FE DEL MUNDO", "DOCTOR FE DEL MUNDO"],
    "BAMBOO": ["BAMBOO"],
    "DOCTOR": ["DOCTOR", "DR"],
    "GREGORIO_ZARA": ["GREGORIO ZARA", "DR GREGORIO ZARA"],
    "TELEPHONE": ["TELEPHONE", "PHONE"],
    "KARAOKE": ["KARAOKE"],
    "LIGHT_BULB": ["LIGHT BULB", "LIGHTBULB"],
    "CHEMICAL_PROPERTY": ["CHEMICAL PROPERTY"],
    "FLAMMABILITY": ["FLAMMABILITY"],
    "REACTIVITY": ["REACTIVITY"],
    "KEROSENE": ["KEROSENE"],
    "BLEACH": ["BLEACH"],
    "MURIATIC_ACID": ["MURIATIC ACID"],
    "RUSTING": ["RUSTING", "RUST"],
    "TOXICITY": ["TOXICITY"],
    "CORROSION": ["CORROSION"],
    "EXPLOSIVE": ["EXPLOSIVE"],
    "BIODEGRADABLE": ["BIODEGRADABLE"],
    "NON_BIODEGRADABLE": ["NON BIODEGRADABLE", "NON-BIODEGRADABLE", "NONBIODEGRADABLE"],
    "BANANA_PEEL": ["BANANA PEEL"],
    "PLASTIC_BOTTLE": ["PLASTIC BOTTLE"],
    "COMPOSTING": ["COMPOSTING"],
    "MICROORGANISMS": ["MICROORGANISMS", "MICRO ORGANISMS", "MICRO-ORGANISMS"],
    "ORGANIC_WASTE": ["ORGANIC WASTE"],
    "ALUMINUM_CAN": ["ALUMINUM CAN", "ALUMINIUM CAN"],
    "GLASS_JAR": ["GLASS JAR"],
    "DECOMPOSERS": ["DECOMPOSERS", "DECOMPOSER"],
    "COMBUSTION": ["COMBUSTION"],
    "IRREVERSIBLE_CHANGE": ["IRREVERSIBLE CHANGE"],
    "ASH": ["ASH"],
    "MELTING": ["MELTING"],
    "TEMPERATURE": ["TEMPERATURE"],
    "REVERSIBLE_CHANGE": ["REVERSIBLE CHANGE"],
    "FREEZING": ["FREEZING"],
    "EVAPORATION": ["EVAPORATION"],
    "HEAT_ENERGY": ["HEAT ENERGY"],
    "EXPANSION": ["EXPANSION"],
    "HARMFUL_CHANGE": ["HARMFUL CHANGE"],
    "WASTE_MANAGEMENT": ["WASTE MANAGEMENT"],
    "TOXIC_FUMES": ["TOXIC FUMES"],
    "PROPER_STORAGE": ["PROPER STORAGE"],
    "RECYCLING": ["RECYCLING"],
    "REUSE": ["REUSE", "RE USE", "RE-USE"],
    "REDUCE": ["REDUCE"],
    "POLLUTION": ["POLLUTION"],
    "SAFETY_LABEL": ["SAFETY LABEL"],
    "BIODEGRADABLE_PIT": ["BIODEGRADABLE PIT"],
    "WATER_POLLUTION": ["WATER POLLUTION"],
    "WASTE_TREATMENT": ["WASTE TREATMENT"],
    "SEGREGATION": ["SEGREGATION"],
    "OPEN_MINDEDNESS": ["OPEN MINDEDNESS", "OPEN-MINDEDNESS"],
    "ENVIRONMENTAL_ISSUE": ["ENVIRONMENTAL ISSUE"],
    "AIR_POLLUTION": ["AIR POLLUTION"],
    "DEFORESTATION": ["DEFORESTATION"],
    "REFORESTATION": ["REFORESTATION"],
    "SOIL_EROSION": ["SOIL EROSION"],
    "MATERIAL_RECOVERY": ["MATERIAL RECOVERY"],
    "SCIENCE_PROCESS_SKILLS": ["SCIENCE PROCESS SKILLS"],
    "OBSERVATION": ["OBSERVATION"],
    "DATA_CLASSIFICATION": ["DATA CLASSIFICATION"],
    "SCIENTIFIC_SURVEY": ["SCIENTIFIC SURVEY"],
    "COMMUNICATION": ["COMMUNICATION"],
    "PREDICTION": ["PREDICTION"],
    "MEASUREMENT": ["MEASUREMENT"],
    "INFERENCE": ["INFERENCE"],
    "QUESTIONNAIRES": ["QUESTIONNAIRES", "QUESTIONNAIRE"],
    "DATA_ANALYSIS": ["DATA ANALYSIS"],
    "MATERIAL": ["MATERIAL", "MATERIALS"],
    "USEFUL_MATERIAL": ["USEFUL MATERIAL", "USEFUL MATERIALS"],
    "HARMFUL_MATERIAL": ["HARMFUL MATERIAL", "HARMFUL MATERIALS"],
    "TOXIC": ["TOXIC"],
    "FLAMMABLE": ["FLAMMABLE"],
    "CORROSIVE": ["CORROSIVE"],
    "SAFETY_SYMBOL": ["SAFETY SYMBOL"],
    "EXPIRATION_DATE": ["EXPIRATION DATE", "EXPIRY DATE"],
    "CONTAINER": ["CONTAINER"],
    "OXIDATION": ["OXIDATION"],
    "FIRE_TRIANGLE": ["FIRE TRIANGLE"],
    "DECOMPOSING": ["DECOMPOSING"],
    "FRESH_APPLE": ["FRESH APPLE"],
    "IRON_OXIDE": ["IRON OXIDE"],
    "FUEL": ["FUEL"],
    "PHYSICAL_CHANGE": ["PHYSICAL CHANGE"],
    "CHEMICAL_CHANGE": ["CHEMICAL CHANGE"],
    "BURNING": ["BURNING"],
    "COOKING": ["COOKING"],
    "REVERSIBLE": ["REVERSIBLE"],
    "IRREVERSIBLE": ["IRREVERSIBLE"],
    "HEAT_APPLICATION": ["HEAT APPLICATION"],
    "MIXTURE": ["MIXTURE"],
    "HOMOGENEOUS": ["HOMOGENEOUS"],
    "HETEROGENEOUS": ["HETEROGENEOUS"],
    "COMPONENT": ["COMPONENT"],
    "HALO_HALO": ["HALO HALO", "HALO-HALO"],
    "SUGAR_SOLUTION": ["SUGAR SOLUTION"],
    "SOLID_SOLID": ["SOLID SOLID", "SOLID-SOLID"],
    "LIQUID_LIQUID": ["LIQUID LIQUID", "LIQUID-LIQUID"],
    "PHASE": ["PHASE"],
    "SOLUTION": ["SOLUTION"],
    "SOLUTE": ["SOLUTE"],
    "SOLVENT": ["SOLVENT"],
    "SUSPENSION": ["SUSPENSION"],
    "COLLOID": ["COLLOID"],
    "TYNDALL_EFFECT": ["TYNDALL EFFECT"],
    "MUDDY_WATER": ["MUDDY WATER"],
    "MAYONNAISE": ["MAYONNAISE"],
    "DISSOLVING": ["DISSOLVING"],
    "SETTLING": ["SETTLING"],
}


def normalize_answer(answer: str | None) -> str:
    normalized = str(answer or "").upper().replace("_", " ")
    normalized = re.sub(r"[^A-Z0-9 ]+", " ", normalized)
    normalized = re.sub(r"\s+", " ", normalized).strip()
    return normalized


def canonicalize_answer(answer: str | None) -> str | None:
    normalized = normalize_answer(answer)
    if not normalized:
        return None

    for canonical, aliases in ANSWER_ALIASES.items():
        if normalized in {normalize_answer(alias) for alias in aliases}:
            return canonical

    direct_label = normalized.replace(" ", "_")
    if direct_label in SUPPORTED_SCIENCE_SIGNS:
        return direct_label
    return None


def canonical_word(word: str | None) -> str:
    return canonicalize_answer(word) or normalize_answer(word).replace(" ", "_")


def answers_match(recognized_answer: str | None, expected_answer: str | None) -> bool:
    expected = canonicalize_answer(expected_answer)
    recognized = canonicalize_answer(recognized_answer)
    if expected is not None or recognized is not None:
        return expected is not None and expected == recognized
    return normalize_answer(expected_answer) == normalize_answer(recognized_answer)


def validate_recognized_answer(recognized_answer: str | None, expected_answer: str | None) -> dict[str, str | bool | None]:
    expected = canonicalize_answer(expected_answer)
    recognized = canonicalize_answer(recognized_answer)
    return {
        "expected_canonical": expected,
        "recognized_canonical": recognized,
        "is_correct": answers_match(recognized_answer, expected_answer),
    }
